openapi: '3.0.3'
info:
  title: 'Calculator API docs - for testing'
  version: '2.0.1'
tags:
  - name: health
    description: Health check
  - name: calculator
    description: Calculator operations
externalDocs:
  url: https://enzophan.github.io/
  description: My calculator documentation