/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/calculator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get all calculations */
        get: operations["getAllCalculations"];
        put?: never;
        /** @description Create a calculation */
        post: operations["createCalculation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculator/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get calculation by ID */
        get: operations["getCalculationById"];
        /** @description Update a calculation */
        put: operations["updateCalculation"];
        post?: never;
        /** @description Delete calculation by ID */
        delete: operations["deleteCalculationById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Health check endpoint for Calculator API */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Calculation command */
        CalculatorCommand: {
            /** @enum {string} */
            operator: "+" | "-" | "*" | "/";
            operand1: number;
            operand2: number;
        };
        /** @description Calculation result */
        CalculatorResult: components["schemas"]["CalculatorCommand"] & {
            /** @description Unique ID of the calculation */
            id: string;
            result?: number;
            message?: string;
            /**
             * @description Number of milliseconds since Epoch time
             * @example 1688612539479
             */
            timestamp: number;
        };
        ErrorModel: {
            message: string;
        };
        /** @description Health check status */
        HealthStatus: {
            /** @enum {string} */
            status: "OK";
            /**
             * @description Number of milliseconds since Epoch time
             * @example 1688612539479
             */
            timestamp: number;
        };
    };
    responses: {
        /** @description Internal server error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
        /** @description Not found error */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorModel"];
            };
        };
    };
    parameters: {
        /** @description Calculator ID */
        CalculatorId: string;
    };
    requestBodies: {
        /** @description Calculator command request body */
        CalculatorCommand: {
            content: {
                "application/json": components["schemas"]["CalculatorCommand"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllCalculations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResult"][];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    createCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CalculatorCommand"];
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResult"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getCalculationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calculator ID */
                id: components["parameters"]["CalculatorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResult"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    updateCalculation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calculator ID */
                id: components["parameters"]["CalculatorId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["CalculatorCommand"];
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResult"];
                };
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteCalculationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Calculator ID */
                id: components["parameters"]["CalculatorId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFoundError"];
            500: components["responses"]["InternalServerError"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
}
