# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: mysql:5.5
    container_name: test-db
    ports:
      - "3306:3306"
    # volumes:
    #   - db_data:/var/lib/mysql
    #   - .:/test-app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user_testdb
      MYSQL_PASSWORD: password

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080