version: '3.7'

services:
  nodets:
    container_name: nodets
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment: 
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/test #Using name of service
    expose:
      - '4000'
    ports:
      - '4000:4000'
    networks:
      - example-net
    depends_on:
      - mongo
    command: node dist/src/app.js
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - example-net
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    networks:
      - example-net
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/

networks:
  example-net:
    external: true
