version: '3.1'

services:
  nodets-app:
    container_name: nodets
    restart: always
    build: .
    environment: 
      - PORT=8000
    ports: 
      - 8000:8000
    networks:
      - example-net
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo_node_ts
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - 27017:27017
    networks:
      - example-net
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    restart: always
    networks:
      - example-net
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/

networks:
  example-net:
    external: true
